module.exports = (sequelize, DataTypes) =>
  sequelize.define(
    "visit",
    {
        visit_time:{
            type:DataTypes.DATE,
            allowNull:false,
        },
        exit_time:{
            type:DataTypes.DATE,
            allowNull:false,
        },
        visit_big:{
            type:DataTypes.STRING(20),
            allowNull:false,
        },
        visit_middle:{
            type:DataTypes.STRING(20),
            allowNull:false,
        },
        visit_small:{
            type:DataTypes.STRING(45),
            allowNull:false,
        },
        create_date:{
            type:DataTypes.DATEONLY,
            allowNull:false,
        },
        modified_date :{
            type:DataTypes.DATEONLY,
            allowNull:false,
        },
        visitor_num:{
            type:DataTypes.INTEGER,
            allowNull:false,
        }
    },{
        timestamps:false,
        paranoid:false,
    }
  );